version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"

volumes:
  redis_data: 